name:                trello-api
version:             0.1.0.0
github:              "rdnetto/trello-api"
license:             Apache
author:              "Reuben D'Netto"
maintainer:          "rdnetto@gmail.com"
copyright:           "Copyright 2018"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/rdnetto/trello-api#readme>

dependencies:
- base >= 4.7 && < 5
- mtl
- servant

# Although we use Prelude in the library itself, Intero gets confused by differences in extensions
default-extensions:
- NoImplicitPrelude
- OverloadedStrings
- ScopedTypeVariables
- TupleSections
- TypeApplications

ghc-options:
- -Wall
- -Wextra
# Sometimes it's just simpler to shadow names from prelude
- -Wno-name-shadowing

library:
  source-dirs: lib
  dependencies:
  - aeson
  - bytestring
  - containers
  - http-api-data
  - http-client
  - http-client-tls
  - http-types
  - mmorph
  - mtl
  - network-uri
  - servant
  - servant-client
  - text
  - time
  - transformers

internal-libraries:
  scraper-lib:
    source-dirs:         scraper/lib
    dependencies:
    - aeson
    - attoparsec
    - attoparsec-time
    - basic-prelude
    - bytestring
    - containers
    - html-entities
    - html-parse
    - microlens
    - microlens-aeson
    - microlens-mtl
    - microlens-th
    - parsec
    - safe
    - scientific
    - text
    - unordered-containers
    - vector
    - yaml

executables:
  # This binary scrapes the Trello website and generates a Swagger spec
  trello-scraper:
    main:                Main.hs
    source-dirs:         scraper/exe
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aeson
    - basic-prelude
    - bytestring
    - containers
    - directory
    - http-conduit
    - microlens
    - microlens-aeson
    - process
    - scraper-lib
    - text
    - unordered-containers
    - yaml


tests:
  scraper_tests:
    main:                Spec.hs
    source-dirs:         scraper/test
    dependencies:
    - aeson
    - basic-prelude
    - raw-strings-qq
    - scraper-lib
    - tasty
    - tasty-hunit
    - text
    - yaml

