name:                trello-api
version:             0.1.0.0
github:              "rdnetto/trello-api"
license:             Apache
author:              "Reuben D'Netto"
maintainer:          "rdnetto@gmail.com"
copyright:           "Copyright 2018"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/rdnetto/steam-trello-sync#readme>

dependencies:
- base >= 4.7 && < 5
- mtl
- servant

# Although we use Prelude in the library itself, Intero gets confused by differences in extensions
default-extensions:
- NoImplicitPrelude
- OverloadedStrings
- ScopedTypeVariables
- TupleSections

library:
  source-dirs: src
  dependencies:
  - http-client-tls
  - servant-client

executables:
  # This binary generates the Servant bindings from the Swagger spec.
  servant-generator:
    main:                Main.hs
    source-dirs:         generator
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - basic-prelude
    - filepath
    - insert-ordered-containers
    - haskell-src-exts
    - microlens
    - microlens-th
    - safe
    - swagger2
    - text
    - yaml

  # This binary scrapes the Trello website and generates a Swagger spec
  trello-scraper:
    main:                Main.hs
    source-dirs:         scraper
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aeson
    - attoparsec
    - basic-prelude
    - bytestring
    - containers
    - filepath
    - http-conduit
    - html-entities
    - html-parse
    - insert-ordered-containers
    - microlens
    - safe
    - swagger2
    - text
    - yaml

