name: trello-api
version: '0.1.0.0'
category: Web
author: Reuben D'Netto
maintainer: rdnetto@gmail.com
copyright: Copyright 2017
license: BSD3
github: rdnetto/trello-api
extra-source-files:
- README.md
dependencies:
- base >=4.7 && <5
library:
  source-dirs: src
  exposed-modules:
  - Lib

name:                trello-api
version:             0.1.0.0
github:              "rdnetto/trello-api"
license:             Apache
author:              "Reuben D'Netto"
maintainer:          "rdnetto@gmail.com"
copyright:           "Copyright 2018"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/rdnetto/steam-trello-sync#readme>

dependencies:
- base >= 4.7 && < 5
- mtl

library:
  source-dirs: src
  dependencies:
  - http-client-tls
  - servant
  - servant-client

# This binary generates the Servant bindings from the Swagger spec.
executables:
  servant-generator:
    main:                Main.hs
    source-dirs:         generator
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    default-extensions:
    - NoImplicitPrelude
    - OverloadedStrings
    - ScopedTypeVariables
    dependencies:
    - basic-prelude
    - swagger2
    - yaml
